project_id = "hsonasdmcklteggrpafd"

[functions.transcribe-audio]
verify_jwt = false

[functions.get-cid-code]
verify_jwt = false

[functions.calculate-age]
verify_jwt = false

[functions.format-pediatric-age]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.examinus-chat]
verify_jwt = false
